### ISSUE TITLE
Visita como objeto valor

### ISSUE THREAD

**Issue by alexespana** [alexespana/BarPower#21]
Como programador, voy a convertir cada visita en un objeto valor para resolver el problema planteado en la HU #9. Para ello voy a definir una clase Visit que sea inmutable y cuyo ciclo de vida dependerá de la clase Visits. Dicha clase tendrá los siguientes atributos:
* **Hora de la visita**: dato de tipo entero
* **Tipo de cliente**(niño,joven.adulto,anciano): dato de tipo str

Este issue está directamente relacionado con la HU #9 .

**Comment by JJ** [comment]
Aunque está bien que detalles las cosas de esta forma, un issue debe ser un problema, y el código la solución. En ningún caso se hará un commit que afecte a dos issues.
