### ISSUE TITLE
Captura de eventos a un nivel superior

### ISSUE THREAD

**Issue by alexespana** [alexespana/barpower#45]
Se necesita realizar la captura de eventos de la aplicación desde un nivel superior para poder cumplir la O de los principio SOLID, **Open/Close**, es decir, tener código abierto a extensión y cerrado a modificación.

Este issue está directamente relacionado con #42 .

**Comment by JJ** [comment]
Los issues deben seguir siendo problemas. Debes decir por qué tienes que capturar los eventos, no plantear la solución en el issue.
